### ISSUE TITLE
SQL Integration

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang-api#32]
At least one SQL integration must be available for beta release. This will be a separate repo but tracking here for beta release milestone.

I will create instrumentation for https://github.com/erleans/pgo but of course Ecto would be a better target if someone has time to do so.

**Comment by hauleth** [comment]
If we get Telemetry integration then it should be available immediately without additional work. This would also solve #31

**Comment by tsloughter** [comment]
Only partly true, as I mention in #31.

Setting up attributes on the span is specific to the type of span. For Ecto we'll have https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-database.md and for Plug/Tesla https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md
