### ISSUE TITLE
Support arrays for attribute values

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang-api#37]

**Comment by julien-leclercq** [comment]
This is actually kind of a bug, in the current state of the repo, `OpenTelemetry.Tracer.with_span` cannot be used with `start_opts` because the type of start_opts is a map and they cannot be used in macros unless they are escaped, but then the underlying code would not work either.

**Comment by tsloughter** [comment]
@julien-leclercq that would be a separate issue you are describing. This is about attributes on a span.

I've not heard of this maps can not be used in macros? Can you open a  new issue.

**Comment by tolbrino** [comment]
> is a map and they cannot be used in macros unless they are escaped, but then the underlying code would not work either.

Could you point to a reference which describes this behaviour? Its actually news to me, therefore I'm asking.

**Comment by julien-leclercq** [comment]
nevermind I did a mistake while defining my own wrapper, forget what I said. Sorry for the message.
