### ISSUE TITLE
mix support for rebar3 git_subdir resource

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/opentelemetry-erlang-api#61]
Rebar3 3.14.0 will have support for a `git_subdir` resource that allows the user to specify the directory in a git repo where an application is found. This is what we should switch opentelemetry-erlang-api/opentelemetry-erlang repos to use and become a single opentelemetry-erlang repository. But we can't do that until mix supports reading in this type of resource from `rebar.config`.

We should also do this for exporters I think. My thinking is that `opentelemetry-beam` org will be used to start exporters, experiments and examples but the exporters will then be merged into a single repo `opentelemetry-erlang-contrib` or something like that. This will make it easier to keep exporters working with the latest Otel releases.

I'm opening this here in hopes someone is interested in adding the mix support :)

**Comment by DianaOlympos** [comment]
Maybe open the issue in the elixir repo directly ? So that it has more visibility and the Core team may comment on what is needed ?

**Comment by tsloughter** [comment]
Their issue template says not to open issues for features.

**Comment by DianaOlympos** [comment]
Fair. I suppose it is a mailing list thing then. Or an elixirforum

**Comment by tsloughter** [comment]
Are you on the list? :)

Someone here must be and also be interested in sending this out to the list to make it visible?

**Comment by DianaOlympos** [comment]
I think the list is open. I am probably as i offered features before. Only problem is that i would have no time to take care of it right now

**Comment by hauleth** [comment]
https://groups.google.com/forum/#!topic/elixir-lang-core/rrqHJmSXlOQ proposed.

**Comment by tsloughter** [comment]
@hauleth thanks but it needs to be clear this is about support for rebar3 subdirs. Mix reads in rebar.config and parses it. Best to just link to this issue I think.

**Comment by tsloughter** [comment]
Completed and repos have been merged: https://github.com/open-telemetry/opentelemetry-erlang
