### ISSUE TITLE
Avoid using "ot" as a shortcut for OpenTelemetry, use "otel"

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-erlang-api#85]
This has the impact of the API that needs to change to use "otel_ctx", "otel_trace", etc.

See https://github.com/open-telemetry/opentelemetry-specification#acronym

**Comment by tsloughter** [comment]
Damn, thanks, didn't know this was official and added to the spec :).

Had settled on `ot_` because there isn't an OpenTracing Erlang lib named `OpenTracing` and using the `ot_` prefix. But with this in the spec I'm for making the changes and will get them knocked out.

**Comment by tsloughter** [comment]
Handled in https://github.com/open-telemetry/opentelemetry-erlang
